<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="446" started-at="2019-10-25T09:47:24Z" finished-at="2019-10-25T09:47:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="446" started-at="2019-10-25T09:47:24Z" finished-at="2019-10-25T09:47:25Z">
      <class name="basic.ExtentReportBasic">
        <test-method status="PASS" signature="startReport()[pri:0, instance:basic.ExtentReportBasic@4501b7af]" name="startReport" is-config="true" duration-ms="123" started-at="2019-10-25T15:17:24Z" finished-at="2019-10-25T15:17:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method status="PASS" signature="test1()[pri:0, instance:basic.ExtentReportBasic@4501b7af]" name="test1" duration-ms="9" started-at="2019-10-25T15:17:24Z" finished-at="2019-10-25T15:17:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:basic.ExtentReportBasic@4501b7af]" name="test2" duration-ms="2" started-at="2019-10-25T15:17:24Z" finished-at="2019-10-25T15:17:24Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at basic.ExtentReportBasic.test2(ExtentReportBasic.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="flush()[pri:0, instance:basic.ExtentReportBasic@4501b7af]" name="flush" is-config="true" duration-ms="291" started-at="2019-10-25T15:17:24Z" finished-at="2019-10-25T15:17:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flush -->
      </class> <!-- basic.ExtentReportBasic -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
